name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install gtest
      run:  apt update -y &&  apt-get install libgtest-dev -y
    - name: make
      run: make
    - name: test 
      run: ./runTest
